-- AlterTable
ALTER TABLE `attachment` MODIFY `updatedAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

-- AlterTable
ALTER TABLE `comment` MODIFY `updatedAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

-- AlterTable
ALTER TABLE `release` MODIFY `updatedAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

-- AlterTable
ALTER TABLE `user` MODIFY `updatedAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
